spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:file:./target/H2DB/where-have-to-lunch;AUTO_SERVER=TRUE
    #    по другому IDEA не отображала содержимое базы данных
    #    url: jdbc:h2:mem:where-have-to-lunch;AUTO_SERVER=TRUE
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  liquibase:
    change-log: classpath:/db/changelog/db-changelog-master.yaml
    enabled: true
